// 01-GettingStarted/client/react/src/App.tsx
import { useEffect } from 'react';
import { RevealSdkSettings, RevealView } from 'reveal-sdk';

RevealSdkSettings.setBaseUrl("http://localhost:5111/");

function App() {

  useEffect(() => {
    new RevealView("#revealView");
  }, []);

  return (
    <div id="revealView" style={{ height: "100vh", width: "100%" }}></div>
  );
}

export default App;

// 01-GettingStarted/client/angular/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { RevealSdkSettings, RevealView } from 'reveal-sdk';

RevealSdkSettings.setBaseUrl("http://localhost:5111");

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit {

  @ViewChild('revealView') el!: ElementRef;

  ngAfterViewInit(): void {
    new RevealView(this.el.nativeElement);
  }

}
